module.exports = {
  bytes: 'bytes',
  color: 'color',
  cstring: 'cstring',
  empty: 'empty',
  fixedString: 'fixedString',
  int32: 'int32',
  links: 'links',
  moduleFlags: 'moduleFlags',
  patternAppearanceFlags: 'patternAppearanceFlags',
  patternFlags: 'patternFlags',
  uint8: 'uint8',
  uint32: 'uint32',
  version: 'version',
}
